// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"encoding/json"
)

// Defines values for EvalHydroResultFailureFailure.
const (
	EvalHydroResultFailureFailureEvalRejected       EvalHydroResultFailureFailure = "eval_rejected"
	EvalHydroResultFailureFailureNetworkUnavailable EvalHydroResultFailureFailure = "network_unavailable"
	EvalHydroResultFailureFailureUnstableScale      EvalHydroResultFailureFailure = "unstable_scale"
)

// Defines values for EvalNewResultFailureFailure.
const (
	EvalNewResultFailureFailureHardwareCheckFailed EvalNewResultFailureFailure = "hardware_check_failed"
	EvalNewResultFailureFailureNetworkUnavailable  EvalNewResultFailureFailure = "network_unavailable"
	EvalNewResultFailureFailureNoStorageRoom       EvalNewResultFailureFailure = "no_storage_room"
)

// Defines values for EvalSpectrumResultFailureFailure.
const (
	EvalSpectrumResultFailureFailureItemRejected       EvalSpectrumResultFailureFailure = "item_rejected"
	EvalSpectrumResultFailureFailureNetworkUnavailable EvalSpectrumResultFailureFailure = "network_unavailable"
)

// Defines values for EvalStoreRequestDomain.
const (
	EvalStoreRequestDomainBuyout   EvalStoreRequestDomain = "buyout"
	EvalStoreRequestDomainPawnshop EvalStoreRequestDomain = "pawnshop"
)

// Defines values for EvalStoreResultFailureFailure.
const (
	EvalStoreResultFailureFailureForbidden          EvalStoreResultFailureFailure = "forbidden"
	EvalStoreResultFailureFailureNetworkUnavailable EvalStoreResultFailureFailure = "network_unavailable"
)

// Defines values for ItemRejectionReason.
const (
	HighWeight  ItemRejectionReason = "high_weight"
	LowSpectrum ItemRejectionReason = "low_spectrum"
	LowWeight   ItemRejectionReason = "low_weight"
	Unconfirmed ItemRejectionReason = "unconfirmed"
	Undescribed ItemRejectionReason = "undescribed"
)

// Defines values for StorageExtractRequestDomain.
const (
	StorageExtractRequestDomainPawnshop StorageExtractRequestDomain = "pawnshop"
	StorageExtractRequestDomainShop     StorageExtractRequestDomain = "shop"
)

// Defines values for StorageExtractResultFailureFailure.
const (
	Forbidden          StorageExtractResultFailureFailure = "forbidden"
	NetworkUnavailable StorageExtractResultFailureFailure = "network_unavailable"
)

// EvalHydroResult defines model for EvalHydroResult.
type EvalHydroResult interface{}

// EvalHydroResultFailure defines model for EvalHydroResultFailure.
type EvalHydroResultFailure struct {
	Failure EvalHydroResultFailureFailure `json:"failure"`

	// Reason why the item is rejected by the Goldex. It's non-empty if evaluation failure is `item_rejected`
	Reason  ItemRejectionReason `json:"reason"`
	Success bool                `json:"success"`
}

// EvalHydroResultFailureFailure defines model for EvalHydroResultFailure.Failure.
type EvalHydroResultFailureFailure string

// EvalHydroResultSuccess defines model for EvalHydroResultSuccess.
type EvalHydroResultSuccess struct {
	// Valuable metal
	Alloy string `json:"alloy"`

	// Fineness in carats
	Carat string `json:"carat"`

	// Evaluation confidence, 1.0 - is confident, 0.0 - is not, 0.8 - is "pretty" confident
	Confidence float64 `json:"confidence"`

	// Millesimal fineness, 585 stands for 58.5%, 999 for 99.9%, 9999 for 99.99%
	Millesimal int64 `json:"millesimal"`

	// Content of the valuable metal in percents
	Purity float64 `json:"purity"`

	// Automatic decision result
	Risky   bool `json:"risky"`
	Success bool `json:"success"`

	// Warnings that should help with decision. For instance, there could be a tungsten covered with gold.
	Warnings []string `json:"warnings"`

	// Weight in grams
	Weight float64 `json:"weight"`
}

// Data depending on success flag
type EvalNewResult interface{}

// EvalNewResultFailure defines model for EvalNewResultFailure.
type EvalNewResultFailure struct {
	Failure EvalNewResultFailureFailure `json:"failure"`
	Success bool                        `json:"success"`
}

// EvalNewResultFailureFailure defines model for EvalNewResultFailure.Failure.
type EvalNewResultFailureFailure string

// EvalNewResultSuccess defines model for EvalNewResultSuccess.
type EvalNewResultSuccess struct {
	// Evaluation ID
	EvalId uint64 `json:"eval_id"`

	// Storage cell address
	StorageCell StorageCell `json:"storage_cell" validate:"required,alphanum,min=2,max=4"`
	Success     bool        `json:"success"`
}

// EvalSpectrumResult defines model for EvalSpectrumResult.
type EvalSpectrumResult interface{}

// EvalSpectrumResultFailure defines model for EvalSpectrumResultFailure.
type EvalSpectrumResultFailure struct {
	Failure EvalSpectrumResultFailureFailure `json:"failure"`

	// Reason why the item is rejected by the Goldex. It's non-empty if evaluation failure is `item_rejected`
	Reason  ItemRejectionReason `json:"reason"`
	Success bool                `json:"success"`
}

// EvalSpectrumResultFailureFailure defines model for EvalSpectrumResultFailure.Failure.
type EvalSpectrumResultFailureFailure string

// EvalSpectrumResultSuccess defines model for EvalSpectrumResultSuccess.
type EvalSpectrumResultSuccess struct {
	// Valuable metal
	Alloy string `json:"alloy"`

	// Fineness in carats
	Carat string `json:"carat"`

	// Millesimal fineness. 585 stands for 58.5%, 999 for 99.9%, 9999 for 99.99%
	Millesimal int64 `json:"millesimal"`

	// Content of the valuable metal in percents
	Purity float64 `json:"purity"`

	// Spectrum data
	Spectrum map[string]float64 `json:"spectrum"`
	Success  bool               `json:"success"`
}

// EvalStoreRequest defines model for EvalStoreRequest.
type EvalStoreRequest struct {
	// Cell occupation operation domain
	Domain EvalStoreRequestDomain `json:"domain" validate:"required,oneof=buyout pawnshop"`
}

// Cell occupation operation domain
type EvalStoreRequestDomain string

// EvalStoreResult defines model for EvalStoreResult.
type EvalStoreResult interface{}

// EvalStoreResultFailure defines model for EvalStoreResultFailure.
type EvalStoreResultFailure struct {
	Failure EvalStoreResultFailureFailure `json:"failure"`
	Success bool                          `json:"success"`
}

// EvalStoreResultFailureFailure defines model for EvalStoreResultFailure.Failure.
type EvalStoreResultFailureFailure string

// EvalStoreResultSuccess defines model for EvalStoreResultSuccess.
type EvalStoreResultSuccess struct {
	// Storage cell address
	Cell    StorageCell `json:"cell" validate:"required,alphanum,min=2,max=4"`
	Success bool        `json:"success"`

	// Unique storage cell operation ID
	Transaction StorageCellTransaction `json:"transaction"`
}

// HardwareEvent defines model for HardwareEvent.
type HardwareEvent struct {
	// Event data
	Data map[string]interface{} `json:"data"`

	// Event name
	Event string `json:"event"`

	// Named hardware
	Name string `json:"name"`
}

// HardwareRequest defines model for HardwareRequest.
type HardwareRequest struct {
	// Method name
	Method string `json:"method" validate:"required"`

	// Named hardware
	Name string `json:"name" validate:"required"`

	// Method params
	Params json.RawMessage `json:"params"`
}

// HardwareResult defines model for HardwareResult.
type HardwareResult struct {
	// Hardware method result
	Result json.RawMessage `json:"result"`
}

// Reason why the item is rejected by the Goldex. It's non-empty if evaluation failure is `item_rejected`
type ItemRejectionReason string

// ProxyRequest defines model for ProxyRequest.
type ProxyRequest struct {
	// Request key-value
	Body map[string]interface{} `json:"body"`

	// Predefined endpoint name
	Endpoint string `json:"endpoint" validate:"required"`
}

// ProxyResult defines model for ProxyResult.
type ProxyResult struct {
	// Result key-value
	Body map[string]interface{} `json:"body"`

	// http status
	HttpStatus int64 `json:"http_status"`
}

// JSONRPC 2.0 request
type Request struct {
	// Request ID
	Id uint64 `json:"id"`

	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Method name
	Method string `json:"method"`
}

// JSONRPC 2.0 result
type Result struct {
	// Request ID
	Id uint64 `json:"id"`

	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Empty result
	Result map[string]interface{} `json:"result"`
}

// StatusResult defines model for StatusResult.
type StatusResult struct {
	BotId    uint64               `json:"bot_id"`
	Features StatusResultFeatures `json:"features"`

	// Internet connectivity
	InternetConnection bool `json:"internet_connection"`

	// Operational status. False if robot is broken or some mandatory hardware is unavailable
	Operational bool `json:"operational"`

	// available optional hardware
	OptionalHardware map[string]bool `json:"optional_hardware"`
	ProjectId        uint64          `json:"project_id"`
}

// StatusResultFeatures defines model for StatusResultFeatures.
type StatusResultFeatures struct {
	// Items storage is a positional storage (has cells to store items)
	PositionalStorage bool `json:"positional_storage"`

	// Items storage is available
	Storage bool `json:"storage"`
}

// Storage cell address
type StorageCell = string

// Unique storage cell operation ID
type StorageCellTransaction = string

// StorageExtractRequest defines model for StorageExtractRequest.
type StorageExtractRequest struct {
	// Storage cell address
	Cell StorageCell `json:"cell" validate:"required,alphanum,min=2,max=4"`

	// Cell release operation domain
	Domain StorageExtractRequestDomain `json:"domain" validate:"required,oneof=shop pawnshop"`
}

// Cell release operation domain
type StorageExtractRequestDomain string

// StorageExtractResult defines model for StorageExtractResult.
type StorageExtractResult interface{}

// StorageExtractResultFailure defines model for StorageExtractResultFailure.
type StorageExtractResultFailure struct {
	Failure StorageExtractResultFailureFailure `json:"failure"`
	Success bool                               `json:"success"`
}

// StorageExtractResultFailureFailure defines model for StorageExtractResultFailure.Failure.
type StorageExtractResultFailureFailure string

// StorageExtractResultSuccess defines model for StorageExtractResultSuccess.
type StorageExtractResultSuccess struct {
	Success bool `json:"success"`

	// Unique storage cell operation ID
	Transaction StorageCellTransaction `json:"transaction"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Standard or implementation-dependent error code
		Code float32 `json:"code"`

		// Error description
		Message string `json:"message"`
	} `json:"error"`

	// Request ID (if presented in request)
	Id *uint64 `json:"id"`

	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`
}

// EvalHydroJSONBody defines parameters for EvalHydro.
type EvalHydroJSONBody = Request

// EvalNewJSONBody defines parameters for EvalNew.
type EvalNewJSONBody = Request

// EvalReturnJSONBody defines parameters for EvalReturn.
type EvalReturnJSONBody = Request

// EvalSpectrumJSONBody defines parameters for EvalSpectrum.
type EvalSpectrumJSONBody = Request

// EvalStoreJSONBody defines parameters for EvalStore.
type EvalStoreJSONBody struct {
	// Request ID
	Id uint64 `json:"id"`

	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Method name
	Method string           `json:"method"`
	Params EvalStoreRequest `json:"params"`
}

// HardwareEventJSONBody defines parameters for HardwareEvent.
type HardwareEventJSONBody struct {
	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Event name
	Method string        `json:"method"`
	Params HardwareEvent `json:"params"`
}

// HardwareJSONBody defines parameters for Hardware.
type HardwareJSONBody struct {
	// Request ID
	Id uint64 `json:"id"`

	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Method name
	Method string          `json:"method"`
	Params HardwareRequest `json:"params"`
}

// InletCloseJSONBody defines parameters for InletClose.
type InletCloseJSONBody = Request

// InletOpenJSONBody defines parameters for InletOpen.
type InletOpenJSONBody = Request

// OutletCloseJSONBody defines parameters for OutletClose.
type OutletCloseJSONBody = Request

// ProxyJSONBody defines parameters for Proxy.
type ProxyJSONBody struct {
	// Request ID
	Id uint64 `json:"id"`

	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Method name
	Method string       `json:"method"`
	Params ProxyRequest `json:"params"`
}

// StatusJSONBody defines parameters for Status.
type StatusJSONBody = Request

// StorageExtractJSONBody defines parameters for StorageExtract.
type StorageExtractJSONBody struct {
	// Request ID
	Id uint64 `json:"id"`

	// JSONRPC version 2.0
	Jsonrpc string `json:"jsonrpc"`

	// Method name
	Method string                `json:"method"`
	Params StorageExtractRequest `json:"params"`
}

// EvalHydroJSONRequestBody defines body for EvalHydro for application/json ContentType.
type EvalHydroJSONRequestBody = EvalHydroJSONBody

// EvalNewJSONRequestBody defines body for EvalNew for application/json ContentType.
type EvalNewJSONRequestBody = EvalNewJSONBody

// EvalReturnJSONRequestBody defines body for EvalReturn for application/json ContentType.
type EvalReturnJSONRequestBody = EvalReturnJSONBody

// EvalSpectrumJSONRequestBody defines body for EvalSpectrum for application/json ContentType.
type EvalSpectrumJSONRequestBody = EvalSpectrumJSONBody

// EvalStoreJSONRequestBody defines body for EvalStore for application/json ContentType.
type EvalStoreJSONRequestBody EvalStoreJSONBody

// HardwareEventJSONRequestBody defines body for HardwareEvent for application/json ContentType.
type HardwareEventJSONRequestBody HardwareEventJSONBody

// HardwareJSONRequestBody defines body for Hardware for application/json ContentType.
type HardwareJSONRequestBody HardwareJSONBody

// InletCloseJSONRequestBody defines body for InletClose for application/json ContentType.
type InletCloseJSONRequestBody = InletCloseJSONBody

// InletOpenJSONRequestBody defines body for InletOpen for application/json ContentType.
type InletOpenJSONRequestBody = InletOpenJSONBody

// OutletCloseJSONRequestBody defines body for OutletClose for application/json ContentType.
type OutletCloseJSONRequestBody = OutletCloseJSONBody

// ProxyJSONRequestBody defines body for Proxy for application/json ContentType.
type ProxyJSONRequestBody ProxyJSONBody

// StatusJSONRequestBody defines body for Status for application/json ContentType.
type StatusJSONRequestBody = StatusJSONBody

// StorageExtractJSONRequestBody defines body for StorageExtract for application/json ContentType.
type StorageExtractJSONRequestBody StorageExtractJSONBody
